/**
 * 78 张韦特塔罗牌完整数据
 * 22 张大阿尔卡纳 + 56 张小阿尔卡纳
 */
const TAROT_DECK = [
  // ==========================================
  // 大阿尔卡纳 (Major Arcana) - 22 张
  // ==========================================
  {
    id: 0, name: "愚者", nameEn: "The Fool", type: "major", suit: "major",
    symbol: "🃡",
    upright_meaning: "新的开始、冒险精神、天真无畏、无限可能",
    reversed_meaning: "鲁莽轻率、犹豫不决、错失良机、盲目乐观",
    description: "愚者牌代表一个全新的起点，你正站在未知的悬崖边，内心充满期待与不安。这趟旅程需要信任与勇气，勇于踏出舒适区，宇宙将在你迈步时为你铺路。",
    keywords: ["开始", "冒险", "自由", "天真", "信任", "旅途"]
  },
  {
    id: 1, name: "魔术师", nameEn: "The Magician", type: "major", suit: "major",
    symbol: "🧙",
    upright_meaning: "创造力、技能、意志力、掌控局面、资源充沛",
    reversed_meaning: "能力不足、欺骗、操纵、计划受阻、天赋被埋没",
    description: "魔术师手持权杖，桌上摆着代表四元素的圣杯、宝剑、权杖和星币——你拥有做成事情所需的全部资源。这张牌提醒你，你比自己想象的更有力量。",
    keywords: ["创造", "能力", "意志", "掌控", "行动", "潜力"]
  },
  {
    id: 2, name: "女祭司", nameEn: "The High Priestess", type: "major", suit: "major",
    symbol: "🔮",
    upright_meaning: "直觉、内在智慧、潜意识、神秘力量、静待时机",
    reversed_meaning: "忽视直觉、保守秘密、情感封闭、缺乏洞见",
    description: "女祭司静坐在两根柱子之间，手握经卷。她代表超越逻辑的深层次直觉和内在智慧。此刻不必急着行动，静下来倾听内心的声音。",
    keywords: ["直觉", "智慧", "潜意识", "等待", "神秘", "内省"]
  },
  {
    id: 3, name: "皇后", nameEn: "The Empress", type: "major", suit: "major",
    symbol: "👑",
    upright_meaning: "丰饶、母性、创造力、自然之美、富足繁荣",
    reversed_meaning: "情感贫瘠、依赖他人、创意枯竭、挥霍浪费",
    description: "皇后安坐于繁茂的花园中，象征丰饶与滋养。这张牌预示收获与成长，你的付出即将开花结果，也提醒你善待自己的身体与情感。",
    keywords: ["丰饶", "母性", "美丽", "创造", "滋养", "繁荣"]
  },
  {
    id: 4, name: "皇帝", nameEn: "The Emperor", type: "major", suit: "major",
    symbol: "👑",
    upright_meaning: "权威、秩序、领导力、稳定结构、规则与纪律",
    reversed_meaning: "暴虐专横、缺乏自律、混乱无序、滥用权力",
    description: "皇帝端坐王座，背后是坚固的山脉。他代表稳定的秩序与强大的执行力。现在你需要建立规划和底线，用理性与纪律推动事物发展。",
    keywords: ["权威", "秩序", "领导", "稳定", "结构", "纪律"]
  },
  {
    id: 5, name: "教皇", nameEn: "The Hierophant", type: "major", suit: "major",
    symbol: "⛪",
    upright_meaning: "传统智慧、精神导师、信仰体系、制度规范",
    reversed_meaning: "打破常规、反叛传统、教条主义、缺乏主见",
    description: "教皇代表着沿袭下来的智慧和传统价值体系。你可能需要寻求导师的指引，或遵循既定的规则和仪式来找到内心的平静与答案。",
    keywords: ["传统", "智慧", "导师", "信仰", "规则", "仪式"]
  },
  {
    id: 6, name: "恋人", nameEn: "The Lovers", type: "major", suit: "major",
    symbol: "💕",
    upright_meaning: "真爱、和谐关系、重要抉择、身心合一",
    reversed_meaning: "感情破裂、错误选择、价值观冲突、信任危机",
    description: "恋人牌不仅关乎爱情，更代表人生中重大的选择。你需要在两条路径中做出发自内心的决定——这个选择将深刻影响你未来的方向。",
    keywords: ["爱情", "选择", "和谐", "关系", "结合", "信任"]
  },
  {
    id: 7, name: "战车", nameEn: "The Chariot", type: "major", suit: "major",
    symbol: "⚔️",
    upright_meaning: "胜利、决心、意志力、克服困难、勇往直前",
    reversed_meaning: "失控、挫败、方向错误、野心过度膨胀",
    description: "战车象征着冲突后的胜利。驾驭黑白两匹狮身人面兽需要强大的意志力——你正在掌控对立的力量，朝着目标坚定前行。",
    keywords: ["胜利", "意志", "前进", "掌控", "征服", "决心"]
  },
  {
    id: 8, name: "力量", nameEn: "Strength", type: "major", suit: "major",
    symbol: "🦁",
    upright_meaning: "内在力量、勇气、耐心、以柔克刚、驯服本能",
    reversed_meaning: "软弱无力、失控、缺乏耐心、被恐惧支配",
    description: "一位女性轻柔地合拢猛狮的嘴——真正的力量不是蛮力，而是用温柔和坚韧驯服内在的野兽。以理解和慈悲克服困难。",
    keywords: ["力量", "勇气", "耐心", "温柔", "慈悲", "韧性"]
  },
  {
    id: 9, name: "隐士", nameEn: "The Hermit", type: "major", suit: "major",
    symbol: "🏮",
    upright_meaning: "内省、独处、追寻真理、深思熟虑、灵魂探索",
    reversed_meaning: "孤独封闭、逃避现实、拒绝指引、过度孤立",
    description: "隐士持灯立于山巅，灯光照亮脚下的一小片路。这张牌呼唤你暂时远离喧嚣，向内求索真正的答案——最好的指引来自你的内心。",
    keywords: ["内省", "独处", "智慧", "求真", "沉思", "引导"]
  },
  {
    id: 10, name: "命运之轮", nameEn: "Wheel of Fortune", type: "major", suit: "major",
    symbol: "🎡",
    upright_meaning: "命运转折、机遇来临、因果循环、顺势而为",
    reversed_meaning: "厄运降临、逆流而行、错失良机、运势低迷",
    description: "命运之轮不停转动，提醒你万事万物皆为周期。好运与厄运都是暂时的，接受变化的本质，把握命运转折中出现的每一个机会。",
    keywords: ["命运", "转折", "机遇", "循环", "变化", "运气"]
  },
  {
    id: 11, name: "正义", nameEn: "Justice", type: "major", suit: "major",
    symbol: "⚖️",
    upright_meaning: "公平公正、真相大白、因果关系、做出裁决",
    reversed_meaning: "不公不正、逃避责任、偏见歧视、法律纠纷",
    description: "正义女神手持天平与剑，象征因果法则。你的每一个决定都会带来相应的后果。这张牌鼓励你客观公正地看待问题，并做出对得起良心的选择。",
    keywords: ["正义", "公平", "真相", "因果", "裁决", "责任"]
  },
  {
    id: 12, name: "倒吊人", nameEn: "The Hanged Man", type: "major", suit: "major",
    symbol: "🪢",
    upright_meaning: "牺牲奉献、换个角度看世界、暂停静待、精神升华",
    reversed_meaning: "无谓牺牲、停滞不前、固执己见、不愿放手",
    description: "倒吊人自愿被悬挂，神情却异常平静。看似被束缚，实则获得了全新的视角。有时候放手不是放弃，而是用一种不同方式理解和接纳。",
    keywords: ["牺牲", "暂停", "视角", "放下", "奉献", "顿悟"]
  },
  {
    id: 13, name: "死神", nameEn: "Death", type: "major", suit: "major",
    symbol: "💀",
    upright_meaning: "转变与重生、结束旧阶段、清理过往、崭新开始",
    reversed_meaning: "抗拒改变、停滞衰退、恐惧终结、无法释怀",
    description: "死神牌并不预示着肉体死亡，而是象征彻底的转变与释放。某些事物必须结束，才能为新生的可能腾出空间——这是自然的循环。",
    keywords: ["转变", "结束", "重生", "释放", "净化", "新生"]
  },
  {
    id: 14, name: "节制", nameEn: "Temperance", type: "major", suit: "major",
    symbol: "🏺",
    upright_meaning: "平衡调和、中庸之道、自我调节、流畅合作",
    reversed_meaning: "失去平衡、过度放纵、冲突对立、节奏紊乱",
    description: "天使将水在两个杯子间来回倾倒，不多不少恰到好处。节制牌呼唤你在生活中寻求平衡，用温和而有耐心的方式融合对立面。",
    keywords: ["平衡", "节制", "调和", "耐心", "融合", "中庸"]
  },
  {
    id: 15, name: "恶魔", nameEn: "The Devil", type: "major", suit: "major",
    symbol: "😈",
    upright_meaning: "欲望束缚、物质沉迷、阴影面、觉察枷锁",
    reversed_meaning: "挣脱束缚、克服心魔、解脱依赖、觉醒自由",
    description: "恶魔牌上的两个人被链条拴住，但那链子其实很宽松。真正困住你的不是外物，而是内心的欲望和恐惧。一旦看清真相，你便能主动挣脱。",
    keywords: ["欲望", "束缚", "阴影", "沉迷", "依赖", "解脱"]
  },
  {
    id: 16, name: "高塔", nameEn: "The Tower", type: "major", suit: "major",
    symbol: "🗼",
    upright_meaning: "突发事件、旧结构崩塌、真相揭露、彻底瓦解",
    reversed_meaning: "逃避危机、延缓崩溃、内部坍塌、勉强维持",
    description: "高塔被闪电击中，人们从崩塌中坠落。这看似灾难，实则是拆除不再适用根基的必然过程。崩塌之后，你会在废墟中找到重建新生之地。",
    keywords: ["崩塌", "突变", "揭露", "危机", "解放", "重建"]
  },
  {
    id: 17, name: "星星", nameEn: "The Star", type: "major", suit: "major",
    symbol: "⭐",
    upright_meaning: "希望之光、信念疗愈、灵感启迪、宁静祥和",
    reversed_meaning: "失去希望、信心动摇、灵感枯竭、颓废绝望",
    description: "经历高塔的冲击后，星星为你带来温柔的疗愈。赤裸的女子在水边倾倒生命之水，代表回归纯真与信任。请相信宇宙始终在守护着你。",
    keywords: ["希望", "疗愈", "灵感", "宁静", "信心", "祝福"]
  },
  {
    id: 18, name: "月亮", nameEn: "The Moon", type: "major", suit: "major",
    symbol: "🌙",
    upright_meaning: "潜意识恐惧、幻象迷惘、直觉梦境、深层情感",
    reversed_meaning: "恐惧消散、真相浮现、迷惘解除、恢复理智",
    description: "月光下的道路朦胧不明，两只狗和狼在嚎叫，水中的龙虾正要爬上岸。月亮牌提醒你对潜意识的恐惧保持觉察，不要被表象迷惑，小心前行。",
    keywords: ["潜意识", "恐惧", "幻觉", "直觉", "梦境", "迷惘"]
  },
  {
    id: 19, name: "太阳", nameEn: "The Sun", type: "major", suit: "major",
    symbol: "☀️",
    upright_meaning: "喜悦幸福、成功光明、活力四射、纯真快乐",
    reversed_meaning: "暂时阴霾、喜悦减半、自信心不足、计划延迟",
    description: "明亮温暖的大太阳照耀着孩子和白马，向日葵高高开放。这张牌是塔罗中最正面的牌之一，意味着你来到了收获喜悦的时刻，一切豁然开朗。",
    keywords: ["喜悦", "成功", "光明", "快乐", "活力", "成就"]
  },
  {
    id: 20, name: "审判", nameEn: "Judgement", type: "major", suit: "major",
    symbol: "📯",
    upright_meaning: "觉醒召唤、重新评估、内在重生、回应使命",
    reversed_meaning: "逃避召唤、自我怀疑、无法释怀、错失觉醒",
    description: "天使吹响号角，墓中的人们起身回应召唤。审判牌代表一个深刻的觉醒时刻，你需要回应内在更高的召唤，从过往中获得领悟，走向全新的自己。",
    keywords: ["觉醒", "召唤", "重生", "审判", "回顾", "使命"]
  },
  {
    id: 21, name: "世界", nameEn: "The World", type: "major", suit: "major",
    symbol: "🌍",
    upright_meaning: "圆满达成、旅程完成、整合统一、成就与祝福",
    reversed_meaning: "功亏一篑、不完整感、停滞不前、缺乏成就感",
    description: "世界牌描绘一个完整的花环，舞者在其中翩翩起舞。它标志着一个阶段的完美收官，你已完成了灵魂的功课，准备好迎接下一个更宽广的循环。",
    keywords: ["圆满", "完成", "整合", "成就", "旅途", "成功"]
  },

  // ==========================================
  // 小阿尔卡纳 (Minor Arcana) - 权杖组 (Wands) - 14 张
  // ==========================================
  { id: 22, name: "权杖王牌", nameEn: "Ace of Wands", type: "minor", suit: "wands", rank: 1,
    symbol: "🪄", upright_meaning: "新创意、激情迸发、行动契机、能量爆发",
    reversed_meaning: "计划延迟、创意枯竭、动力不足、方向错误",
    description: "一只手臂从云中伸出，紧握发芽的权杖——神秘灵感和新起点已经降临。抓住这份激情的火花，勇敢开始新项目或新冒险。",
    keywords: ["灵感", "开始", "激情", "行动", "创造", "能量"] },
  { id: 23, name: "权杖二", nameEn: "Two of Wands", type: "minor", suit: "wands", rank: 2,
    symbol: "🪄", upright_meaning: "长远规划、展望未来、做出决定、拓展视野",
    reversed_meaning: "犹豫不决、规划失败、眼光狭窄、畏惧未知",
    description: "人物站在城堡上，一手持权杖，一手扶地球仪俯瞰世界。现在需要做出展望未来的大决定，对前方的可能性保有信心。",
    keywords: ["规划", "决策", "远见", "展望", "抱负", "进展"] },
  { id: 24, name: "权杖三", nameEn: "Three of Wands", type: "minor", suit: "wands", rank: 3,
    symbol: "🪄", upright_meaning: "远航出发、合作扩展、等待成果、海外机遇",
    reversed_meaning: "计划受挫、延误返航、合作破裂、失望而归",
    description: "站在山崖边眺望远方海面的商船，你的筹划正在变为现实。耐心等待回音，初期的成功已经在路上。",
    keywords: ["扩展", "远见", "合作", "等待", "探索", "成长"] },
  { id: 25, name: "权杖四", nameEn: "Four of Wands", type: "minor", suit: "wands", rank: 4,
    symbol: "🪄", upright_meaning: "庆祝、稳定家园、完成里程碑、和谐团聚",
    reversed_meaning: "不安定、家庭纠纷、庆祝中断、缺乏归属感",
    description: "四根权杖撑起花环，人们欢庆舞蹈——一个项目完成或家庭的重要里程碑已经到来。值得庆祝和分享。",
    keywords: ["庆祝", "家园", "稳定", "和谐", "完成", "欢乐"] },
  { id: 26, name: "权杖五", nameEn: "Five of Wands", type: "minor", suit: "wands", rank: 5,
    symbol: "🪄", upright_meaning: "竞争冲突、意见分歧、良性竞争、突破瓶颈",
    reversed_meaning: "避免冲突、内耗消停、妥协和解、回避竞争",
    description: "五个人手持权杖似乎在打斗，这代表良性的竞争和冲突。不同的观点碰撞反而可能激发出更好的方案。",
    keywords: ["竞争", "冲突", "分歧", "挑战", "活跃", "突破"] },
  { id: 27, name: "权杖六", nameEn: "Six of Wands", type: "minor", suit: "wands", rank: 6,
    symbol: "🪄", upright_meaning: "胜利凯旋、公众认可、自信提升、领导地位",
    reversed_meaning: "骄傲自负、失败丢脸、认可延迟、地位不稳",
    description: "骑士骑着白马，头戴桂冠光荣归来。你所付出的努力得到了大家的认可，这是属于你的高光时刻。",
    keywords: ["胜利", "认可", "自信", "凯旋", "荣誉", "成功"] },
  { id: 28, name: "权杖七", nameEn: "Seven of Wands", type: "minor", suit: "wands", rank: 7,
    symbol: "🪄", upright_meaning: "坚守立场、抵御挑战、捍卫信念、勇敢对峙",
    reversed_meaning: "被动退让、放弃抵抗、过度防御、信心不足",
    description: "一个人站在高处奋力抵挡下方的攻击，虽然困难但你必须坚持自己的立场。拿出勇气守护你的信念。",
    keywords: ["坚持", "防御", "勇气", "挑战", "立场", "毅力"] },
  { id: 29, name: "权杖八", nameEn: "Eight of Wands", type: "minor", suit: "wands", rank: 8,
    symbol: "🪄", upright_meaning: "飞速进展、消息传来、行动加速、旅行顺利",
    reversed_meaning: "延迟停滞、消息阻隔、计划中断、冲动行事",
    description: "八根权杖划过晴空飞速前进，所有阻碍都已清除。事情正在以极快的速度推进，好消息即将到来。",
    keywords: ["速度", "进展", "消息", "行动", "旅行", "畅通"] },
  { id: 30, name: "权杖九", nameEn: "Nine of Wands", type: "minor", suit: "wands", rank: 9,
    symbol: "🪄", upright_meaning: "最后的坚持、韧性防御、接近终点、伤痕累累",
    reversed_meaning: "放弃挣扎、防御过度、精力耗尽、固执不化",
    description: "头上缠着绷带的人仍握着权杖戒备——你已经走了很远，虽然疲惫，但离成功只差最后一步，再坚持一下。",
    keywords: ["坚持", "韧性", "防备", "接近", "毅力", "疲惫"] },
  { id: 31, name: "权杖十", nameEn: "Ten of Wands", type: "minor", suit: "wands", rank: 10,
    symbol: "🪄", upright_meaning: "负担过重、责任压迫、努力完成、压力巅峰",
    reversed_meaning: "卸下重担、学会说不、推卸责任、压力崩塌",
    description: "一个人背着十根沉重的权杖，前方还有很长的路。你承担了太多，需要审视哪些责任是真正属于你的，适当放手让身心休息。",
    keywords: ["负担", "压力", "责任", "过度", "劳累", "放手"] },
  { id: 32, name: "权杖侍从", nameEn: "Page of Wands", type: "minor", suit: "wands", rank: 11,
    symbol: "🪄", upright_meaning: "新消息、好奇心、学习热情、冒险精神",
    reversed_meaning: "坏消息、拖延计划、浅尝辄止、缺乏方向",
    description: "年轻的侍从手持权杖，眼中充满好奇和探索欲。一个振奋人心的消息或新灵感即将出现，以开放和好奇心迎接它。",
    keywords: ["好奇", "消息", "学习", "探索", "热情", "年轻"] },
  { id: 33, name: "权杖骑士", nameEn: "Knight of Wands", type: "minor", suit: "wands", rank: 12,
    symbol: "🪄", upright_meaning: "激情行动、冒险追求、快速出击、魅力四射",
    reversed_meaning: "冲动鲁莽、半途而废、不计后果、急躁冒进",
    description: "骑士骑着烈马狂奔，充满激情和干劲。行动的时候到了——但务必三思而后行，不要让激情冲昏了头脑。",
    keywords: ["行动", "激情", "冒险", "冲动", "魅力", "追求"] },
  { id: 34, name: "权杖女王", nameEn: "Queen of Wands", type: "minor", suit: "wands", rank: 13,
    symbol: "🪄", upright_meaning: "温暖自信、独立魅力、领导才能、创造力强",
    reversed_meaning: "支配欲强、嫉妒自负、暴躁易怒、过度控制",
    description: "权杖女王坐在向日葵装饰的王座上，阳光自信且乐于助人。她提醒你像她一样散发温暖和力量，带领身边的人前进。",
    keywords: ["温暖", "自信", "独立", "魅力", "领导", "创造"] },
  { id: 35, name: "权杖国王", nameEn: "King of Wands", type: "minor", suit: "wands", rank: 14,
    symbol: "🪄", upright_meaning: "远见领导、创业精神、荣誉责任、强大执行力",
    reversed_meaning: "专横跋扈、期望过高、无法贯彻、暴躁严苛",
    description: "权杖国王端坐王座，手握开花的权杖，笃定而充满远见。他象征着成熟的领导力和创业精神，以愿景和热情激发他人。",
    keywords: ["领导", "远见", "荣誉", "创业", "执行力", "成熟"] },

  // ==========================================
  // 小阿尔卡纳 (Minor Arcana) - 圣杯组 (Cups) - 14 张
  // ==========================================
  { id: 36, name: "圣杯王牌", nameEn: "Ace of Cups", type: "minor", suit: "cups", rank: 1,
    symbol: "🏆", upright_meaning: "新感情、爱的开始、直觉开启、情感满溢",
    reversed_meaning: "情感空虚、爱被拒绝、压抑感受、创意枯竭",
    description: "一只圣杯从云中递出，五道水流倾泻入水面——代表纯粹的情感、新恋情或深层直觉的开启。敞开心扉去接纳甜蜜的馈赠。",
    keywords: ["爱", "情感", "直觉", "开始", "喜悦", "丰盈"] },
  { id: 37, name: "圣杯二", nameEn: "Two of Cups", type: "minor", suit: "cups", rank: 2,
    symbol: "🏆", upright_meaning: "两情相悦、合作结盟、和谐关系、相互尊重",
    reversed_meaning: "感情破裂、信任崩塌、不平等付出、分离",
    description: "男女互相交换圣杯，头顶有双蛇杖狮子翼。这张牌代表真诚的伙伴关系——无论是爱情还是商业合作，都在平等和爱中建立。",
    keywords: ["恋爱", "合作", "和谐", "平等", "伙伴", "联结"] },
  { id: 38, name: "圣杯三", nameEn: "Three of Cups", type: "minor", suit: "cups", rank: 3,
    symbol: "🏆", upright_meaning: "欢庆聚会、友情深厚、团结合作、感恩分享",
    reversed_meaning: "过度放纵、朋友失和、聚会失控、表面热闹",
    description: "三位少女举杯欢庆，脚下是丰收的果实和花朵。这是友情的牌——与亲朋好友分享喜悦，庆祝每一个值得纪念的时刻。",
    keywords: ["庆祝", "友情", "团聚", "欢乐", "感恩", "分享"] },
  { id: 39, name: "圣杯四", nameEn: "Four of Cups", type: "minor", suit: "cups", rank: 4,
    symbol: "🏆", upright_meaning: "沉思不满、重新评估、拒绝机会、冥想内观",
    reversed_meaning: "重拾动力、抓住机会、摆脱麻木、勇敢接受",
    description: "一个人坐在树下抱臂沉思，上方云中伸出的手递来一只新圣杯你却没看见。你正沉浸在自己的厌倦中，可机会其实就在眼前。",
    keywords: ["冷漠", "沉思", "不满", "机会", "内省", "拒绝"] },
  { id: 40, name: "圣杯五", nameEn: "Five of Cups", type: "minor", suit: "cups", rank: 5,
    symbol: "🏆", upright_meaning: "悲伤失落、聚焦损失、遗憾后悔、走出悲伤",
    reversed_meaning: "接受现实、看到希望、从悲痛中学习、宽恕",
    description: "黑袍人低头凝视三只倒下的圣杯，却忽略了身后依然站立的两个。损失是痛苦的，但不要忘了你仍拥有的美好。",
    keywords: ["悲伤", "损失", "遗憾", "失望", "希望", "宽恕"] },
  { id: 41, name: "圣杯六", nameEn: "Six of Cups", type: "minor", suit: "cups", rank: 6,
    symbol: "🏆", upright_meaning: "美好回忆、怀旧温情、纯真善良、馈赠礼物",
    reversed_meaning: "沉溺过去、无法前行、童年阴影、依赖他人",
    description: "一个孩子向另一个女孩递上插满花朵的圣杯——温柔的回忆和纯真的善意正在流淌。此刻很适合感恩过去带来的温暖。",
    keywords: ["回忆", "怀旧", "纯真", "善良", "馈赠", "过去"] },
  { id: 42, name: "圣杯七", nameEn: "Seven of Cups", type: "minor", suit: "cups", rank: 7,
    symbol: "🏆", upright_meaning: "幻想选择、白日梦、多重诱惑、需要聚焦",
    reversed_meaning: "清醒选择、消除幻象、脚踏实地、明确目标",
    description: "七只圣杯漂浮在云朵上，盛放着珠宝、城堡、龙……你面前有太多眼花缭乱的选择。不要被幻象迷惑，看清自己真正想要的。",
    keywords: ["幻想", "选择", "诱惑", "梦想", "迷惑", "聚焦"] },
  { id: 43, name: "圣杯八", nameEn: "Eight of Cups", type: "minor", suit: "cups", rank: 8,
    symbol: "🏆", upright_meaning: "离开现状、寻找更深处意义、情感远行",
    reversed_meaning: "徘徊不走、害怕改变、留恋舒适、迷茫徘徊",
    description: "一个人背对着堆叠的八只圣杯，走向远处的荒山。你正在主动选择离开已经不再滋养你的环境，去寻找更深层的精神满足。",
    keywords: ["离开", "追寻", "舍弃", "远行", "意义", "转变"] },
  { id: 44, name: "圣杯九", nameEn: "Nine of Cups", type: "minor", suit: "cups", rank: 9,
    symbol: "🏆", upright_meaning: "愿望成真、满足喜悦、心想事成、舒适自得",
    reversed_meaning: "得意忘形、愿望落空、贪得无厌、表面满足",
    description: "一个人心满意足地坐在九只圣杯前——这张牌被称为'愿望牌'。你的愿望正在或即将实现，尽情享受这份满足感吧。",
    keywords: ["满足", "愿望", "成功", "喜悦", "感恩", "实现"] },
  { id: 45, name: "圣杯十", nameEn: "Ten of Cups", type: "minor", suit: "cups", rank: 10,
    symbol: "🏆", upright_meaning: "家庭幸福、完美圆满、情感归属、和谐之巅",
    reversed_meaning: "家庭不和、幸福破裂、理想破灭、貌合神离",
    description: "在彩虹下，一对夫妇张开双臂仰望十只圣杯组成的彩虹，旁边有两个孩子在玩耍。这是最幸福的家庭牌——你找到了真正的情感归宿。",
    keywords: ["幸福", "家庭", "圆满", "归属", "和谐", "爱"] },
  { id: 46, name: "圣杯侍从", nameEn: "Page of Cups", type: "minor", suit: "cups", rank: 11,
    symbol: "🏆", upright_meaning: "创意灵感、直觉消息、浪漫邀请、情感萌芽",
    reversed_meaning: "情绪孩子气、创意受阻、表白被拒、不切实际",
    description: "侍从穿着艺术气息的衣服，圣杯中奇妙地探出一条鱼——一个浪漫的消息或创意灵感正在接近，以温柔和好奇接纳它。",
    keywords: ["灵感", "浪漫", "直觉", "消息", "创意", "温柔"] },
  { id: 47, name: "圣杯骑士", nameEn: "Knight of Cups", type: "minor", suit: "cups", rank: 12,
    symbol: "🏆", upright_meaning: "浪漫追求、魅力提案、情感邀约、诗意行动",
    reversed_meaning: "情感欺骗、虚伪浪漫、空头承诺、想法不落地",
    description: "骑士身着鱼纹铠甲缓缓前行，手持圣杯仿佛是呈上最诚挚的邀请。一段温柔的追求或美好创意即将到来，但要确保对方是真诚的。",
    keywords: ["浪漫", "追求", "邀请", "诗意", "理想", "魅力"] },
  { id: 48, name: "圣杯女王", nameEn: "Queen of Cups", type: "minor", suit: "cups", rank: 13,
    symbol: "🏆", upright_meaning: "深刻同理、直觉力量、情感关怀、疗愈慈悲",
    reversed_meaning: "情感依赖、过度敏感、心境抑郁、情绪绑架",
    description: "女王坐在海边抱着精心雕刻的圣杯，强烈同理心使她成为最好的倾听者和疗愈者。请用你的善意照亮他人。",
    keywords: ["同理心", "直觉", "关怀", "疗愈", "慈悲", "敏感"] },
  { id: 49, name: "圣杯国王", nameEn: "King of Cups", type: "minor", suit: "cups", rank: 14,
    symbol: "🏆", upright_meaning: "情感成熟、睿智包容、情绪稳定、艺术修养",
    reversed_meaning: "情绪失控、操控情感、冷漠抽离、压抑真心",
    description: "国王坐在海上的王座中，象征他能够驾驭最深沉的情感波澜而不被淹没。以成熟的智慧处理情感问题，稳重且充满关怀。",
    keywords: ["成熟", "包容", "情绪稳定", "智慧", "艺术", "关怀"] },

  // ==========================================
  // 小阿尔卡纳 (Minor Arcana) - 宝剑组 (Swords) - 14 张
  // ==========================================
  { id: 50, name: "宝剑王牌", nameEn: "Ace of Swords", type: "minor", suit: "swords", rank: 1,
    symbol: "⚔️", upright_meaning: "清晰思路、真理显现、果断切割、智力突破",
    reversed_meaning: "思维混乱、错误判断、真相遮蔽、武断决定",
    description: "一只手臂从云中举起锋利的宝剑，剑尖戴着王冠——代表真理像刀一样切穿迷雾。一个新的洞见即将帮助你做出关键决策。",
    keywords: ["真理", "清晰", "决断", "智力", "突破", "正义"] },
  { id: 51, name: "宝剑二", nameEn: "Two of Swords", type: "minor", suit: "swords", rank: 2,
    symbol: "⚔️", upright_meaning: "艰难抉择、闭目回避、僵持平衡、需要信息",
    reversed_meaning: "信息过载、被迫选择、做出决定、打破僵局",
    description: "蒙眼女子双手交叉持剑，把自己保护起来——你正在面对一个难以做出的决定。与其匆忙行动，不如先摘下蒙眼布收集更多信息。",
    keywords: ["抉择", "僵局", "回避", "平衡", "困惑", "信息"] },
  { id: 52, name: "宝剑三", nameEn: "Three of Swords", type: "minor", suit: "swords", rank: 3,
    symbol: "⚔️", upright_meaning: "心碎悲伤、创伤揭示、情感痛苦、说出真相",
    reversed_meaning: "愈合开始、压抑痛苦、拒绝接受、无法释怀",
    description: "三把剑穿透红心的画面虽然刺痛，但这也是真相终于被说出的时刻。接受这份痛苦是疗愈的起点。",
    keywords: ["心碎", "悲伤", "创伤", "真相", "痛苦", "疗愈"] },
  { id: 53, name: "宝剑四", nameEn: "Four of Swords", type: "minor", suit: "swords", rank: 4,
    symbol: "⚔️", upright_meaning: "休息恢复、冥想静养、暂避冲突、身心修复",
    reversed_meaning: "躁动不安、提前出关、无法休息、焦虑失眠",
    description: "一个人双手合十躺在教堂中，三把剑悬挂于墙而一把在身旁——你已战斗太久，现在需要一场深度休息和心灵的安息。",
    keywords: ["休息", "恢复", "冥想", "宁静", "休养", "暂停"] },
  { id: 54, name: "宝剑五", nameEn: "Five of Swords", type: "minor", suit: "swords", rank: 5,
    symbol: "⚔️", upright_meaning: "冲突胜利但代价大、争执、傲慢伤人、空虚胜出",
    reversed_meaning: "和解希望、妥协、矛盾平息、并反思冲突",
    description: "胜者捡起地上的剑，负者离场——这不一定是真的胜利，反而可能是以牺牲关系换来的。想想这场'胜利'值不值得。",
    keywords: ["冲突", "胜负", "代价", "争执", "傲慢", "和解"] },
  { id: 55, name: "宝剑六", nameEn: "Six of Swords", type: "minor", suit: "swords", rank: 6,
    symbol: "⚔️", upright_meaning: "渡过难关、缓慢疗愈、从困境驶向平静、远行",
    reversed_meaning: "无法离开、困在原地、情感负担沉重、拒绝前行",
    description: "小船载着六把剑驶离风暴水域前往平静彼岸——虽然过程缓慢，但你正在远离那些纷扰。带着过往的经验，继续前行。",
    keywords: ["过渡", "疗愈", "离开", "平静", "远行", "前行"] },
  { id: 56, name: "宝剑七", nameEn: "Seven of Swords", type: "minor", suit: "swords", rank: 7,
    symbol: "⚔️", upright_meaning: "策略取巧、暗中进行、机巧战术、独立思考",
    reversed_meaning: "真相揭露、策略暴露、自食其果、诚实面对",
    description: "一个人踮着脚尖从敌营偷走五把剑——你需要灵活运用智慧，用非传统的方式取得优势。但暗地行动也有风险。",
    keywords: ["策略", "取巧", "机敏", "独立", "隐藏", "智慧"] },
  { id: 57, name: "宝剑八", nameEn: "Eight of Swords", type: "minor", suit: "swords", rank: 8,
    symbol: "⚔️", upright_meaning: "自我束缚、思维受限、恐惧困境、被蒙蔽感",
    reversed_meaning: "自由解脱、突破思维限制、摘掉眼罩、看清现实",
    description: "蒙眼女子被八把剑包围——看似恐怖的束缚其实大多是自己想象出来的。摘下眼罩你就能看清其实是有出路的。",
    keywords: ["束缚", "恐惧", "限制", "困境", "思维", "解脱"] },
  { id: 58, name: "宝剑九", nameEn: "Nine of Swords", type: "minor", suit: "swords", rank: 9,
    symbol: "⚔️", upright_meaning: "焦虑失眠、噩梦缠身、过度担忧、内心折磨",
    reversed_meaning: "焦虑缓解、正视恐惧、接受帮助、痛苦减轻",
    description: "深夜女子醒来掩面哭泣，九把剑悬挂墙面——挥之不去的焦虑和负面思绪在深夜最响亮。请把你的担忧说出来，它们往往没有想象中严重。",
    keywords: ["焦虑", "失眠", "恐惧", "担忧", "噩梦", "释放"] },
  { id: 59, name: "宝剑十", nameEn: "Ten of Swords", type: "minor", suit: "swords", rank: 10,
    symbol: "⚔️", upright_meaning: "痛苦的结束、最低谷、彻底的终结、新的开始",
    reversed_meaning: "拒绝结束、重复痛苦、无法翻身、持续崩溃",
    description: "十把剑钉在趴在地上的身影中——虽然画面触目惊心，但这其实是痛苦的底线，已经不能再更糟了。黎明已在不远处。",
    keywords: ["终结", "最低谷", "痛苦", "结束", "黎明", "重生"] },
  { id: 60, name: "宝剑侍从", nameEn: "Page of Swords", type: "minor", suit: "swords", rank: 11,
    symbol: "⚔️", upright_meaning: "求知欲、理性沟通、信息搜集、警觉机敏",
    reversed_meaning: "言语刻薄、心智不成熟、八卦谣言、缺乏专注",
    description: "侍从举剑而立，眼中充满求知的渴望。一个重要的信息或对话即将出现，保持好奇和理性的头脑去迎接。",
    keywords: ["求知", "沟通", "信息", "理智", "警觉", "好奇"] },
  { id: 61, name: "宝剑骑士", nameEn: "Knight of Swords", type: "minor", suit: "swords", rank: 12,
    symbol: "⚔️", upright_meaning: "迅速行动、直言不讳、敏捷思维、追求真理",
    reversed_meaning: "鲁莽冲动、言语伤人、不计后果、横冲直撞",
    description: "骑士高举宝剑策马全速狂奔——行动和决定都需要立即执行。但务必保证目标清晰，不要因为速度而误伤无辜。",
    keywords: ["迅速", "直言", "敏捷", "行动", "决断", "勇猛"] },
  { id: 62, name: "宝剑女王", nameEn: "Queen of Swords", type: "minor", suit: "swords", rank: 13,
    symbol: "⚔️", upright_meaning: "敏锐洞察、独立理性、公正判断、清晰界限",
    reversed_meaning: "冷酷苛刻、偏见武断、过度理性、冷漠无情",
    description: "女王端坐，一手举剑一手张开，代表对真理的掌握和公正的审判力。她的智慧来自于亲历痛苦后的透彻洞察。",
    keywords: ["敏锐", "独立", "公正", "理性", "洞察", "界限"] },
  { id: 63, name: "宝剑国王", nameEn: "King of Swords", type: "minor", suit: "swords", rank: 14,
    symbol: "⚔️", upright_meaning: "权威智识、逻辑判断、理性掌权、客观决策",
    reversed_meaning: "威严滥施、冷酷裁决、滥用信息、独断专横",
    description: "宝剑国王以坚不可摧的理性治理——以事实和逻辑说话，不因情绪左右判断。他是最高层面的客观智慧。",
    keywords: ["权威", "逻辑", "理智", "判断", "客观", "公正"] },

  // ==========================================
  // 小阿尔卡纳 (Minor Arcana) - 星币组 (Pentacles) - 14 张
  // ==========================================
  { id: 64, name: "星币王牌", nameEn: "Ace of Pentacles", type: "minor", suit: "pentacles", rank: 1,
    symbol: "🪙", upright_meaning: "新财富机遇、实物回报、投资、稳扎稳打",
    reversed_meaning: "错失金钱良机、投资失误、物质不稳定",
    description: "云中递出一只手捧着一枚星币，下方是通向远方的花园之门。一个新的物质机遇或事业根基正在形成，请切实地把握住。",
    keywords: ["财富", "机遇", "投资", "物质", "根基", "稳固"] },
  { id: 65, name: "星币二", nameEn: "Two of Pentacles", type: "minor", suit: "pentacles", rank: 2,
    symbol: "🪙", upright_meaning: "平衡多任务、灵活调整、时间管理、适应变化",
    reversed_meaning: "手忙脚乱、失去平衡、财务混乱、无法兼顾",
    description: "一个人舞动着连在两枚星币上的∞符号——你正在多线作战，需要灵活地平衡时间与资源。相信自己有能力处理。",
    keywords: ["平衡", "灵活", "多任务", "适应", "管理", "变化"] },
  { id: 66, name: "星币三", nameEn: "Three of Pentacles", type: "minor", suit: "pentacles", rank: 3,
    symbol: "🪙", upright_meaning: "团队合作、专业技能、扎实进展、匠心品质",
    reversed_meaning: "合作不畅、质量控制差、缺乏投入、各自为政",
    description: "雕刻师、修士与设计师共商大教堂的蓝图——一个需要团队协作才能完成的细致工程。专注并珍视每一位伙伴的优势。",
    keywords: ["合作", "专业", "技能", "团队", "踏实", "匠心"] },
  { id: 67, name: "星币四", nameEn: "Four of Pentacles", type: "minor", suit: "pentacles", rank: 4,
    symbol: "🪙", upright_meaning: "持有财富、节约保守、对安全感执着、控制欲",
    reversed_meaning: "财务放开、分享慷慨、放手恐惧、过度花销",
    description: "一个人紧紧抱着星币不放——出于对安全的渴望你正在紧握资源。适当的储蓄是好习惯，但过度保守也会错失应有的生活乐趣。",
    keywords: ["保存", "保守", "安全", "掌控", "吝啬", "释放"] },
  { id: 68, name: "星币五", nameEn: "Five of Pentacles", type: "minor", suit: "pentacles", rank: 5,
    symbol: "🪙", upright_meaning: "物质困境、孤独无助、被排挤感、寻求帮助",
    reversed_meaning: "走出贫困、找到援助、重新融入、逐渐好转",
    description: "风雪中两人衣衫褴褛经过灯火通明的教堂却选择不进去——援助其实就在身边。别因为羞愧而拒绝向外求援。",
    keywords: ["困境", "贫穷", "孤独", "求助", "接纳", "援助"] },
  { id: 69, name: "星币六", nameEn: "Six of Pentacles", type: "minor", suit: "pentacles", rank: 6,
    symbol: "🪙", upright_meaning: "施与受、慈善慷慨、资源分配、公平分享",
    reversed_meaning: "不平等的施与、施舍姿态、财务损失、吝啬",
    description: "商人一手持天平，一手给跪地的乞丐发放星币。此刻你可以是给予者也可以是接受者，关键在于资源和感恩的平衡。",
    keywords: ["给予", "接受", "慷慨", "分享", "公平", "慈善"] },
  { id: 70, name: "星币七", nameEn: "Seven of Pentacles", type: "minor", suit: "pentacles", rank: 7,
    symbol: "🪙", upright_meaning: "耐心等待收获、评估进展、长期投入、反思方向",
    reversed_meaning: "前功尽弃、不耐烦、回报延迟、投入无效",
    description: "园丁倚锄看着结满星币的藤蔓——你的辛勤付出正在生长，虽然没有立即可见的回报。花点时间评估进度，再做下一步决定。",
    keywords: ["耐心", "收获", "评估", "投入", "等待", "反思"] },
  { id: 71, name: "星币八", nameEn: "Eight of Pentacles", type: "minor", suit: "pentacles", rank: 8,
    symbol: "🪙", upright_meaning: "勤勉专注、打磨技艺、持续进步、追求卓越",
    reversed_meaning: "敷衍了事、工作倦怠、缺乏动力、粗制滥造",
    description: "学徒全神贯注地敲打一枚又一枚星币——这是专注和钻研的化身。在日复一日的打磨中，你的技艺将达到新的高度。",
    keywords: ["勤勉", "专注", "技能", "打磨", "进步", "匠人"] },
  { id: 72, name: "星币九", nameEn: "Nine of Pentacles", type: "minor", suit: "pentacles", rank: 9,
    symbol: "🪙", upright_meaning: "独立富足、享受成果、自我犒赏、优雅安逸",
    reversed_meaning: "财务依赖、挥霍无度、不安全感、粗俗浪费",
    description: "优雅的女子独自从葡萄藤下走过，肩上站着一只鸟儿——她凭自己的努力过上了富足而独立的生活。这呼唤你享受属于你的安逸。",
    keywords: ["富足", "独立", "享受", "优雅", "成就", "安逸"] },
  { id: 73, name: "星币十", nameEn: "Ten of Pentacles", type: "minor", suit: "pentacles", rank: 10,
    symbol: "🪙", upright_meaning: "财富传承、家族稳固、长期保障、物质丰碑",
    reversed_meaning: "家族纠纷、遗产问题、物质崩盘、世家没落",
    description: "三人世代同堂，老人、城堡、家犬与排列的星币象征富足的积累已超越个人，传承至家族和社会的层面。你正在建立起真正的财富地基。",
    keywords: ["传承", "稳固", "财富", "家族", "长期", "成就"] },
  { id: 74, name: "星币侍从", nameEn: "Page of Pentacles", type: "minor", suit: "pentacles", rank: 11,
    symbol: "🪙", upright_meaning: "学习实践、踏实上进、新的学习契机、财务初阶",
    reversed_meaning: "学习怠惰、不切实际、好高骛远、资源浪费",
    description: "少年双手捧着星币仔细端详——你正处在学习和积累的初期阶段。带着务实谦逊的好奇心，准备好获得新技能吧。",
    keywords: ["学习", "实践", "踏实", "务实", "机会", "潜力"] },
  { id: 75, name: "星币骑士", nameEn: "Knight of Pentacles", type: "minor", suit: "pentacles", rank: 12,
    symbol: "🪙", upright_meaning: "耐心务实、可靠执行、稳定推进、逐步达成",
    reversed_meaning: "拖延怠惰、一成不变、缺乏创新、进度停滞",
    description: "骑士骑在厚重黑马上静静地持着星币——他不匆忙，也不放弃，以沉稳步调向目标推进。任何事情急不来，稳扎稳打。",
    keywords: ["务实", "耐心", "可靠", "执行", "稳重", "坚持"] },
  { id: 76, name: "星币女王", nameEn: "Queen of Pentacles", type: "minor", suit: "pentacles", rank: 13,
    symbol: "🪙", upright_meaning: "务实滋养、持家有道、舒适丰足、实际关怀",
    reversed_meaning: "忽视家事、财务紊乱、冷漠淡泊、物质至上",
    description: "女王轻抚着膝上的星币被繁花包围——她懂得如何用物质世界滋养每一个人，既有富裕的能力也有温暖细致的爱心。",
    keywords: ["滋养", "务实", "富足", "关怀", "持家", "温暖"] },
  { id: 77, name: "星币国王", nameEn: "King of Pentacles", type: "minor", suit: "pentacles", rank: 14,
    symbol: "🪙", upright_meaning: "财富帝王、商业头脑、稳如磐石、最终成功",
    reversed_meaning: "为富不仁、赌徒心理、物质主义、财务腐朽",
    description: "国王坐在满布牛头与葡萄纹样装饰的王座上——他拥有最稳定可靠的物质成就。提醒你以长远的眼光创造不受动摇的财富基础。",
    keywords: ["财富", "成功", "稳健", "商业", "权威", "成就"] }
];

// 花色中英文对照
const SUIT_NAMES = {
  wands: "权杖",
  cups: "圣杯",
  swords: "宝剑",
  pentacles: "星币"
};

const SUIT_EMOJIS = {
  wands: "🪄",
  cups: "🏆",
  swords: "⚔️",
  pentacles: "🪙"
};

// 正逆位文案
const DIRECTION_LABELS = {
  upright: "✨ 正位",
  reversed: "🔄 逆位"
};